#CRAN packages
usethis::use_package("tibble")
usethis::use_package("reticulate")
usethis::use_package("amap")
usethis::use_package("Rmagic")
usethis::use_package("data.table")
usethis::use_package("parallel")
usethis::use_package("Matrix")
usethis::use_package("Seurat")
usethis::use_package("agrmt")
usethis::use_package("data.tree")
usethis::use_package("collapsibleTree")
usethis::use_package("randomForest")
usethis::use_package("caret")
usethis::use_package("dplyr")
usethis::use_package("plyr")
usethis::use_package("ROCit")
usethis::use_package("set")
usethis::use_package("cutoff")
usethis::use_package("copykat")
usethis::use_package("htmlwidgets")
usethis::use_package("stringr")
usethis::use_package("foreach")
usethis::use_package("doParallel")
usethis::use_package("forcats")
usethis::use_pipe()
usethis::use_package("scales")
usethis::use_package("future")

#edit description file to have diff min versions
